<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="src\Infrastructure\Export\" />
    <Folder Include="src\Infrastructure\Import\" />
    <Folder Include="src\Infrastructure\Commands\" />
  </ItemGroup>

</Project>
